@rootUrl = http://localhost:8000

#Status Check

### get user
GET {{rootUrl}}

### insert new user

POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "fName":"Sushil",
    "lName":"Dangoriya",
    "email":"d@d.com",
    "password":"123"
}